### PR TITLE
fix(dio): upgrade dartastic_opentelemetry_api to beta.6 and fix OTel context in tests

### PR DESCRIPTION
**Pull request by benjaben**
## Summary

- Bumps `dartastic_opentelemetry_api` from `^1.0.0-alpha` to `^1.0.0-beta.6` in both `embrace` and `embrace_dio` to align with the beta.6 APIs already used in the `embrace` package (introduced in #856b8fa).
- Fixes two OTel traceparent tests in `embrace_dio` that started a span via `startSpan` but never attached it to the current context. The interceptor's `W3cTraceContext.injectCurrentSync` only injects when a span is active in `Context.current`, so the tests now wrap `dio.get` in `tracer.withSpanAsync(span, ...)`.

## Test plan

- [x] `flutter test` in `embrace_dio` passes all 16 tests (was failing with compilation errors and 2 test failures)
- [x] `flutter test` in `embrace` continues to pass

### CODE REVIEW

**Review by fractalwrench — APPROVED** [review]
LGTM
